version: '2.2'

services:
  app:
    image: 'ddss-catalog:latest'
    build:
      context: .
    container_name: ddss-catalog-app
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - db
    command: sh -c './wait-for host:5432'
    env_file:
      - vars-spring.env
          
  db:
    image: 'postgres:14.2-alpine'
    container_name: ddss-catalog-db
    networks:
      - my-network
    env_file:
      - vars-postgres.env

networks:
  my-network:
    external: true